apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: default
  namespace: default
rules:
- apiGroups:
  - ""
  resources: # Here are resources you can access
  - pods
  - endpoints
  - services
  verbs: # That is what you can do with them
  - get
  - list
  - watch
  - create
  - update
  - delete
  - patch
