apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: common-disk-azurefile-pv-claim
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: azurefile
  resources:
    requests:
      storage: 1Gi
