---
apiVersion: v1
kind: Service
metadata:
  name: glusterfs-cluster 
spec:
  ports:
  - port: 1
---
apiVersion: v1
kind: Endpoints
metadata:
  name: glusterfs-cluster 
subsets:
  - addresses:
      - ip: 192.168.1.243
    ports:
      - port: 1 
  - addresses:
      - ip: 192.168.1.244
    ports:
      - port: 1
