kind: ReplicationController
apiVersion: v1
metadata:
  name: spark-master-controller
spec:
  replicas: 1
  selector:
    component: spark-master
  template:
    metadata:
      labels:
        component: spark-master
    spec:
      serviceAccountName: spark
      containers:
        - name: spark-master
          image: kaustav4284/spark-2.4:navicore
          imagePullPolicy: Always
          env:
          - name: SPARK_SERVICE_NAME
            value: "spark-master"
          command: ["/start-master"]
          ports:
            - containerPort: 7077
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m

