apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
clusterDNS:
- 10.96.0.10

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: influxdb
  namespace: monitoring
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: influxdb
        task: monitoring
    spec:
      containers:
      - image: kaustav4284/influxdb001:firstbuild
        name: influxdb
        ports:
        - containerPort: 8086
          protocol: TCP
---      
apiVersion: v1
kind: Service
metadata:
  labels:
    task: monitoring
    # For use as a Cluster add-on (https://github.com/kubernetes/kubernetes/tree/master/cluster/addons)
    # If you are NOT using this as an addon, you should comment out this line.
    
  name: influxdb
  namespace: monitoring
spec:
  ports:
  - port: 8086
    targetPort: 8086
  selector:
    name: influxdb
  type: NodePort



