apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: influxdb
  namespace: monitoring
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: influxdb
        task: monitoring
    spec:
      containers:
      - image: kaustav4284/influxdb001:firstbuild
        name: influxdb
        ports:
        - containerPort: 8086
          protocol: TCP
---      
apiVersion: v1
kind: Service
metadata:
  labels:
    task: monitoring
    
  name: influxdb
  namespace: monitoring
spec:
  ports:
  - port: 8086
    name: api
    protocol: TCP
    targetPort: 8086
  - port: 8083
    name: http
    protocol: TCP
    targetPort: 8083
  selector:
    name: influxdb
  type: NodePort



