# An example of a Kubernetes configuration for Ignite pods deployment.
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  # Custom Ignite cluster's name.
  name: kafka-producer-client
spec:
  # A number of Ignite pods to be started by Kubernetes initially.
  replicas: 2
  template:
    metadata:
      labels:
        app: ignite
    spec:
      
      serviceAccountName: ignite
      
      containers:
        # Custom Ignite pod name.
      - name: ignite-producer-client-node
        image: kaustav4284/kafka-kube-producer01:firsttry
               
        ports:
        # Ports to open.
        # Might be optional depending on your Kubernetes environment.
        - containerPort: 8080 # REST port number.
        - containerPort: 47100 # communication SPI port number.
        - containerPort: 47500 # discovery SPI port number.
        - containerPort: 49112 # JMX port number.
        - containerPort: 10800 # SQL port number.
        - containerPort: 10900 # Thin clients port number.
          

