apiVersion: v1
kind: Pod
metadata:
  name: gpu-pod3
spec:
  containers:
    - name: cuda-container
      image: nvidia/cuda:9.0-devel
      env:
      - name: DP_DISABLE_HEALTHCHECKS
        value: "xids"
      
    - name: digits-container
      image: nvidia/digits:6.0
      env:
      - name: DP_DISABLE_HEALTHCHECKS
        value: "xids"
      
